### ISSUE TITLE
document how to create an account first time

### ISSUE THREAD

**Issue by eccegordo** [kiwiupover/ember-cli-surge#11] opened 2016-04-02 18:33 UTC
As a first time surge.sh user it was a little unclear how to create an account until I realized I had to run the surge command directly.

I think part of the problem is that when I ran the `ember surge` command from my ember project folder the line wraps in the CLI and so I can't create a surge account. Here is a screen grab that shows the issue.

<img width="661" alt="surge-line-wrap" src="https://cloud.githubusercontent.com/assets/497659/14228335/a035137a-f8c6-11e5-88e2-805b00db11e8.png">

**Comment by kiwiupover** [comment] 2016-04-04 23:34
G’day Mate 

Thanks for trying out `ember-cli-surge`

You need to create an account and login before running `ember surge`.

I would like to make ember-cli-surge work with creating an account in the middle of running `ember surge` that is the next feature for this project.

Cheers
Dave


-- 
Dave Laird
Sent with Airmail

On April 2, 2016 at 11:33:52 AM, Gordon Potter (notifications@github.com) wrote:

As a first time surge.sh user it was a little unclear how to create an account until I realized I had to run the surge command directly.

I think part of the problem is that when I ran the ember surge command from my ember project folder the line wraps in the CLI and so I can't create a surge account. Here is a screen grab that shows the issue.

**Comment by zinthose** [comment] 2016-04-20 06:51
Adding my 2 cents into this.
I tried to used ember-cli-surge today and also getting the same issue..
When I run a surge whoami I get the expected listing for my logged in account but when I run ember surge I get the login prompt.

**Comment by kiwiupover** [comment] 2016-04-20 15:08
I agree I will add a bit more about creating a user at surge

**Comment by jasalguero** [comment] 2016-04-27 10:18
I'm in the same situation, actually I created the user with surge, but still do "ember serge" and get stuck there... if I put my existing email it does nothing..

**Comment by kiwiupover** [comment] 2016-05-14 23:16
@eccegordo @rtablada 

#12 is a fix for this issue.

Can you test by updating your package.json
From: 
`"ember-cli-surge": "1.0.6"` 
To: to 
`"ember-cli-surge": "git://github.com/kiwiupover/ember-cli-surge#42bbb21ade7efeaaa0202813da0189628791c677",`

You will need to run `ember generate ember-cli-surge` then  `ember surge` in your project.

**Comment by eccegordo** [comment] 2016-05-15 08:30
@kiwiupover 
I get a "cannot find module lodash/includes" error when I try to run the generator again.

I have wiped node_modules and reinstalled.

```
$ ember generate ember-cli-surge
Cannot find module 'lodash/includes'
Error: Cannot find module 'lodash/includes'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (path-to-my-app/node_modules/ember-cli-surge/lib/commands/surge.js:4:17)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

**Comment by eccegordo** [comment] 2016-05-15 08:40
@jasalguero There is a manual workaround. You have to have to login to surge using the regular `surge` command. Then go edit your `.netrc` file in your home directory.

Your .netrc file will look something like this

```
machine surge.surge.sh
    login me@example.com
    password some-long-checksum
```

But you need to add a `machine surge.sh` entry.

Something like this

```
machine surge.sh
    login me@example.com
    password some-long-checksum
machine surge.surge.sh
    login me@example.com
    password some-long-checksum
```

At this point the ember surge command should work.

**Comment by kiwiupover** [comment] 2016-05-16 05:49
Thanks for all the comments here. @eccegordo @jasalguero @zinthose please let me know how the latest version 1.1.0 works for you. 

Cheers

**Closed** 2016-05-16 05:50 UTC
